### PR TITLE
US15-Task62 Pass data from API to charts

### PR DESCRIPTION
**Pull request by shahih25**
US15-Task62 Pass data from API to charts

### CODE REVIEW

**Comment by shahih25** [comment]
Screenshot 2024-02-10 at 11 58 53 PM
Screenshot 2024-02-10 at 11 59 00 PM
Screenshot 2024-02-10 at 11 59 08 PM

**Comment by shahih25** [comment]
Screenshot 2024-02-11 at 12 22 12 AM

**Comment by spark290** [comment]
US15Task62 PR review 1
US15Task62 PR review 2
US15Task62 PR review 3
Works well

**Comment by achaur11** [comment]
Looks good to me.

**Review by achaur11 — APPROVED** [review]

**Pull request merged**
