### PR TITLE
US21-Task99 Add threshold field and member dropdown

### PR DESCRIPTION
**Pull request by shahih25**
US21-Task99 Add threshold field and member dropdown

### CODE REVIEW

**Comment by shahih25** [comment]
Screenshot 2024-02-24 at 12 52 43 PM

**Comment by shahih25** [comment]
Screenshot 2024-02-24 at 4 18 10 PM

**Comment by spark290** [comment]
Works fine
Screenshot

**Comment by AdvaitChirmule** [comment]
Looks good to me

**Pull request merged**
