### PR TITLE
[US112 Task117] Run Flake8 and Remove Violations

### PR DESCRIPTION
**Pull request by shahih25**
[US112 Task117] Run Flake8 and Remove Violations

### CODE REVIEW

**Comment by shahih25** [comment]
Screenshot 2024-03-15 at 2 30 47 PM
Screenshot 2024-03-15 at 2 30 54 PM
Screenshot 2024-03-15 at 2 31 10 PM
Screenshot 2024-03-15 at 2 31 14 PM
Screenshot 2024-03-15 at 2 32 12 PM

**Comment by shahih25** [comment]
Screenshot 2024-03-15 at 3 35 14 PM

**Comment by spark290** [comment]
Graph for 5 metrics works well in this branch

**Pull request merged**
